name: Version Bump

on:
  workflow_dispatch:
    inputs:
      publish-docker-image:
        description: 'Publish docker image?'
        type: boolean
        required: true
        default: true

jobs:
  version-bump:
    runs-on: ubuntu-latest
    outputs:
      old-version: ${{ steps.step-version-bump.outputs.OLD_VERSION }}
      new-version: ${{ steps.step-version-bump.outputs.NEW_VERSION }}

    steps:
      - uses: actions/checkout@master

      - name: Version bump
        id: step-version-bump
        uses: papermerge/banger@master
        with:
          files_list: "package.json,app/version.js"

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "version bump ${{steps.step-version-bump.outputs.OLD_VERSION}} -> ${{steps.step-version-bump.outputs.NEW_VERSION}}" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  build-and-publish-image-to-docker-hub:
    name: Dockerhub build/push
    needs: version-bump
    if: ${{ github.event.inputs.publish-docker-image == 'true' }}    
    runs-on: ubuntu-latest

    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: papermerge/papermerge.js:${{needs.version-bump.outputs.new-version}}
          file: docker/Dockerfile

  build-and-push-image-to-ghcr:
    name: ghcr.io build/push
    if: ${{ github.event.inputs.publish-docker-image == 'true' }}
    needs: version-bump    
    runs-on: ubuntu-latest    

    env:
      papermerge_js_image: ghcr.io/papermerge/papermerge.js

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          tags: ${{ env.papermerge_js_image }}:${{needs.version-bump.outputs.new-version}}, ${{ env.papermerge_js_image }}:latest
          file: docker/Dockerfile
